@startuml
title {{cookiecutter.node_classname}} Sequence Diagram
actor User as user
participant {{cookiecutter.node_classname}} as node
participant {{cookiecutter.process_classname}} as process
participant Logger as logger

alt initialize
    activate node
    node -> node++: start()
    node -> process++: {{cookiecutter.process_classname}}()
    node -> node: preinitialize_basenode()
    node -> process: enable_diagnostics()
    node -> process: finish_initialization()
    node -> node: finish_initialization()
    node -> process: request_statechange(RUNNING,override=true)
    node--
end

alt messages
    alt Command
        user -> node++: command_Callback(cmd)
        node -> process++: new_commandmsg(cmd)
        process --> node--: diag_list
        node --> logger: log_diag(diag_list)
    end
end
alt loops
    alt loop1
        node -> node++: run_loop1
        node--
    end
    alt loop2
        node -> node++: run_loop2
        node--
    end
    alt loop3
        node -> node++: run_loop3
        node--
    end
    
    alt run_01hz_noisy
        node -> process: pretty()
        process --> node: str
        node -> logger: log_debug(str)
    end
    alt run_1hz
        node -> process: get_latest_diagnostics()
        process --> node: latest_diagnostics
        node -> user: publish(latest_diagnostics)
    end
    alt run_10hz
        node -> process: update(0.1, now)
        process --> node: diag
        alt if diag.level >= NOTICE
            node -> logger: log_diagnostic(diag)
        end
        node -> process: get_diagnostics()
        process --> node: diagnostics
        node -> node: update_diagnostics(diagnostics)
        node -> process: get_ready_to_arm()
        process --> node: ready_to_arm
        node -> node: update_ready_to_arm(ready_to_arm)

    end
end
@enduml