@startuml
title System Monitor Window Class Diagram
package eros {
    class ArmDisarm
    class heartbeat <<(M,#FFFF00)>>
    class resource <<(M,#FFFF00)>>
    class loadfactor <<(M,#FFFF00)>>
}
package eros_window {
    interface IWindow
    abstract BaseWindow
    IWindow <|.. BaseWindow
}
package eros_nodes::SystemMonitor {
    class DeviceWindow #LimeGreen {
        +bool update(double dt, double t_ros_time)
        +bool new_msg(eros::ArmDisarm::State armed_state) // NO-OP
        +bool new_msg(eros::heartbeat heartbeat_msg) // NO-OP
        +bool new_msg(eros::resource resource_msg)
        +bool new_msg(eros::loadfactor loadfactor_msg)
        -bool update_window()

    }
    BaseWindow <|-- DeviceWindow
    class NodeWindow #LimeGreen {
        +bool update(double dt, double t_ros_time)
        +bool new_msg(eros::ArmDisarm::State armed_state) // NO-OP
        +bool new_msg(eros::heartbeat heartbeat_msg)
        +bool new_msg(eros::resource resource_msg)
        +bool new_msg(eros::loadfactor loadfactor_msg) // NO-OP
        -bool update_window()
        
    }
    BaseWindow <|-- NodeWindow
    class InstructionWindow #LimeGreen {
        +bool update(double dt, double t_ros_time)
        +bool new_msg(eros::ArmDisarm::State armed_state) // NO-OP
        +bool new_msg(eros::heartbeat heartbeat_msg)
        +bool new_msg(eros::resource resource_msg)
        +bool new_msg(eros::loadfactor loadfactor_msg) // NO-OP
        -bool update_window()
        
    }
    BaseWindow <|-- InstructionWindow
}
@enduml