@startuml
title System Monitor Utility Class Diagram
package curses {
    class WINDOW
}
package eros_nodes {
package SystemMonitor {
    struct eros_window::ScreenCoordinatePixel
    class eros_window::CommonWindowUtility #LimeGreen {
        {static} WINDOW* create_newwin(int height, int width, int starty, int startx)
        {static} +eros_window::ScreenCoordinatePixel create_newwin(int height, int width, int starty, int startx)
    }
}
}
@enduml